### ISSUE TITLE
An event for reach bottom of listview

### ISSUE THREAD

**Issue by miladhashemi** [os-js/osjs-gui#38]
It's better to have an event when we reach to end of the list.

**Comment by andersevenrud** [comment]
I've added the action `scroll` to the listview where you get an event as the argument. You can use `ev.target` to calculate any point, not just the bottom.

```
const scrollContainer = ev.target
const hitBottom = (el.scrollTop + el.innerHeight) >= el.scrollHeight
```

**Comment by mahsashadi** [comment]
Hi.

We are considering extending the FileManager Application, to support gradual fetching of data by scrolling down.

The VFS adapter should support **readdir with limitation**. For example in _readdir_  function of our VFS adapter we should consider two **limit** (number of returned items) and **marker** (the last item previously returned) parameters.

Since some Adapters may support this feature and some not, what is the best suggestion to add this feature in FileManager Application?

**Comment by andersevenrud** [comment]
The best solution for this is to create an interface in the VFS that can be used in options so that all adapters that supports this feature will use the same arguments when using the API.

**Comment by mahsashadi** [comment]
By **interface in the VFS**, you mean we should develop another VFS service-provider that expose _readdirLimited_ method, in addition to other methods like _readdir_, _readfile_, ....?

**Comment by andersevenrud** [comment]
I mean into the VFS API:

```javascript
// usage
vfs.readdir('mount:/path', {
  // new interface
  page: {
    size: Number,
    token: String
  }
})

// adapter
function readdir(path, options) {
  fetch('http://localhost', {
    body: JSON.stringify({
      limit: options.page.size,
      marker: options.page.token
    })
  })
}
```

**Comment by mahsashadi** [comment]
Is this client-side _options_ accessibile in server-side VFS adapter?

 Whatever I add in _options_ client-side in file-manager, server-side VFS adapter _options_ only contains _session_ object.

**Comment by andersevenrud** [comment]
All options are passed along to the server-side adapter. But it actually looks like the `readdir` in the default system adapter explicitly sets options to `{}` (which is not right).

**Comment by andersevenrud** [comment]
Also, this is off-topic now. Start a new issue please :)
